### ISSUE TITLE
NullReferenceException when creating proxy with constructor initialized properties

### ISSUE THREAD

**Issue by darkcamper** [mfidemraizer/trackerdog#16]
When I try to create a proxy from a class that assigns a value to a property from the constructor a NullReferenceException is thrown.

I know that calling virtual member functions from the constructor can cause problems, but the property is only virtual because it is necessary for proxy creation.

I have added a new test to ProxyCreationTest.cs that reproduces this issue.

**Comment by FranckDepoortere** [comment]
I've got the same issue too.

**Comment by mfidemraizer** [comment]
@FranckDepoortere  It's already fixed, but I need that the lazy @darkcamper can update the pull request (note he's a friend of mine :P)

**Comment by mfidemraizer** [comment]
Because of some personal affairs, @darkcamper couldn't fix the associated pull request, thus, I've already fixed this issue and I've provided a simple test case demonstrating that it already works!

TrackerDog NuGet package v2.1.1 is already available.
