### ISSUE TITLE
Class with read-only properties throwing exceptions cause problems

### ISSUE THREAD

**Issue by mfidemraizer** [mfidemraizer/trackerdog#17]
Copy-pasted from [issue 14](https://github.com/mfidemraizer/trackerdog/issues/14#issuecomment-239701714) from a comment of @FranckDepoortere

The factory cannot build the object because of this property. My explanation is below:

```
    public string ObjectBuilder
    {
        get
        {   // In my case, this exception can exist for differents reasons: 
            // we need to keep former implementation to stay compliant 
            // to a previous interface
            // Sometime, we dont have implemented the interface yet.

            throw new NotImplementedException();
        }
    }
```

**Comment by mfidemraizer** [comment]
@FranckDepoortere I've tried to configure this type:

```
    public class ClassWithReadOnlyPropertyThrowingException
    {
        public virtual string Text
        {
            get { throw new InvalidOperationException(); }
        }
    }
```

And I've configured it as follows:

```
var config = ObjectChangeTracking.CreateConfiguration();
config.TrackThisType<ClassWithReadOnlyPropertyThrowingException>();
```

And later I've created a trackable object using this code:

`TrackableObjectFactory.CreateOf<ClassWithReadOnlyPropertyThrowingException>();`

This has thrown no exception at all...

Sadly I believe that we need to be more efficient, because simple issues are taking ages to get solved, because I need to be guessing what's going on in your use cases (like in #14).

The best you can do whenever you fill an issue in any project is **very important to provide a test case that drives the library to the bug.** You might think that it's easier to throw a partial code and let the author find the problem, but I honestly think that you're mistaken: it's easier that you show the error with a working code, and then, let the author solve it :)

Don't get me wrong, I love solving issues on TrackerDog, but if you want quicker solutions I need that you could provide a test case for every bug you fill here unless it's very obvious and I can reproduce it myself.

So... will you provide me a simplified test case? 

Thank you in advance

**Comment by FranckDepoortere** [comment]
I'm sorry: I had the pb in the testcase yesterday. (https://github.com/mfidemraizer/trackerdog/files/417292/MyTest.cs.txt)
It's solved with the zipped version today.

Thanks
Franck

**Comment by mfidemraizer** [comment]
@FranckDepoortere  Ok! Good news! So I close this issue then :D
