### ISSUE TITLE
Cannot track dictionary property changes

### ISSUE THREAD

**Issue by mfidemraizer** [mfidemraizer/trackerdog#2]
In current version there's a bug. While TrackerDog can track changes of collection properties, when a property is `IDictionary<TKey, TValue`, it'll throw an exception.

**Comment by mfidemraizer** [comment]
This issue had two underlying problems:

1. TrackerDog wasn't adding a collection tracking configuration for `IDictionary<TKey, TValue>`.
2. Collection change tracking wasn't supporting the special case of `IDictionary<TKey, TValue>` where items are `KeyValuePair<TKey, TValue>` instead of the actual objects to be tracked for changes.

For now, I've partially solved the issue: now TrackerDog can track `IDictionary<TKey, TValue>` property changes, but it won't know which key-value pairs were changed nor it won't be able to track dictionary values if they're of some trackable type.

**Comment by darthkurak** [comment]
I wonder if this somehow was resolved? Or still, dictionary values cannot be tracked?
