### ISSUE TITLE
Collection change tracking not working

### ISSUE THREAD

**Issue by mfidemraizer** [mfidemraizer/trackerdog#22]
@gtmacgregor has found a problem when trying to track changes on some collection property on issue #21 

Let's move the discussion to this new issue.

Description:

> I am having an issue with getting collection change info. I tried to follow the examples to get the IReadOnlyChangeTrackableCollection by:
> 
> IReadOnlyChangeTrackableCollection c = (IReadOnlyChangeTrackableCollection)entity.Contacts; 
> 
> Contacts returns an IList<Contact> but I get a runtime error when the above is executed: 
> 
> Unable to cast object of type 'System.Collections.Generic.List`1[Contact]' to type 'TrackerDog.IReadOnlyChangeTrackableCollection'.
> 
> An I missing something?
> 
> Thanks
> 
>  Glenn

And:

> @mfidemraizer 
> 
> I did some digging and found in your tests when you create a trackable WhateverParent from an existing WhateverParent in CollectionItemsArePreservedWhenTurningParentObjectIntoTrackable the list are also proxied. Meaning before the object is trackable List and List2 are just Lists but after the CreateFrom the tracked object List and List2 types are now IList Proxy. This is not happening for my object:
> 
> `
> Customer {
> private IList<Contact> mContacts = new List<Contact>();
> ...
> public virtual IList<Contact> Contacts 
> {
>    get { return mContacts;}
>    set mContacts = value.ToList();}
> }
> `
> 
> So when I create a trackable Customer the type of Contacts is still the list and not the IList proxy. All the objects in the list are proxy objects as I have configured that property to be tracked as well as the Contact object.
> 
> Thanks
> 
>  Glenn

**Comment by mfidemraizer** [comment]
@gtmacgregor

Maybe I'm mistaken, but I guess the issue is the whole `Contacts` collection property setter! :D

`set { mContacts = value.ToList(); }`

When you call `Enumerable.ToList<T>(...)` you're turning the proxy into a regular `List<T>` again.

So... just try to remove that `Enumerable.ToList<T>(...)` call and see what happens. 

Let me know if this was the issue! I'll look forward for your comments.

**Comment by gtmacgregor** [comment]
@mfidemraizer 

Working great, thank you for all your help!

**Comment by mfidemraizer** [comment]
@gtmacgregor  Nice! Check that I've released TrackerDog 2.1.4 becuase I found some bugs and I've already fixed them (I'm using this project in my workplace). Maybe they wouldn't affect you at all, but it shouldn't be a bad idea that you upgrade your NuGet package to 2.1.4.

Let's close this issue. If you find any further problem or you need guidance, I'll be always happy to assist you ;)
