### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by mfidemraizer** [mfidemraizer/trackerdog#25]
It would be great that TrackerDog could also work on .NET Core.

**Comment by mfidemraizer** [comment]
It seems like this can be possible because Castle Project is already working on the 4th version of [Castle DynamicProxy supporting .NET Core.](https://github.com/castleproject/Core/releases).

In the other hand, I believe that I'll need to perform a small refactor on current code base because of the differences of .NET Framework and .NET Core in terms of how to access type metadata. `GetType()` vs `GetType().GetTypeInfo()`.

So I'll try to work on this in the next days.

**Comment by HamedFathi** [comment]
@mfidemraizer

please provide .net core version as soon as possible :)

**Comment by mfidemraizer** [comment]
@HamedFathi 

Hey, thank you for your support! ;)

My concern is TrackerDog is built on top of Castle DynamicProxy, which still doesn't own a production-ready release on .NET Core. 

AFAIK, their last release was [Castle Core 4.0.0-Beta002](https://github.com/castleproject/Core/blob/master/CHANGELOG.md) and it happened on 28 of October of 2016 and the most recent commit was on 15 of Novembre of 2016.

Actually, .NET Core is supported since the first alpha version of Castle Core. Maybe we can move on with this version while they advance to a production-ready version. 

In my case, I'll need to refactor some parts of TrackerDog's codebase because I checked that .NET core accesses type metadata using [`TypeInfo`](https://msdn.microsoft.com/en-us/library/system.reflection.typeinfo(v=vs.110).aspx).

Ideally, TrackerDog should work on any .NET Standard-compliant .NET runtime...

If you or anyone has found a dynamic proxy generator which already works on .NET Core and it has been already declared for production use, it would be useful that you and others could provide me a link. For now, I've not found any alternative to Castle DynamicProxy on .NET Core.

**Comment by mfidemraizer** [comment]
Update: I've been trying to start the migration to .NET Core, but I found a big issue. 

Since .NET Core is abandoning `project.json` in favor of getting back to `csproj` (MSBuild) format, there's still bad support for the whole format on Visual Studio Code. I could try to start the migration on Visual Studio 2017 RC, but it's a long installation and usually I try to work with RTM Visual Studio versions to avoid advancing work that might require more changes once Visual Studio goes gold.

Conclusion: I'll be aware about OmniSharp support to `csproj` format and once they got it, I'll try again to configure my dev machine to work on the whole migration...

**Comment by mfidemraizer** [comment]
Good news! Caslte Core 4.0.0 is out https://github.com/castleproject/Core/releases/tag/v4.0.0

And it comes with .NET Core support. This is the definitive step to work out TrackerDog to be compatible with .NET Core too!

**Comment by mfidemraizer** [comment]
@HamedFathi I've already published TrackerDog 2.2.0 which is a .NET Standard 1.3 library and it can be used in .NET Core 1.0 and newer versions!

If you find any problem or bug, feel free to fill an issue and I'll try to fix it as soon as possible!

**Comment by HamedFathi** [comment]
@mfidemraizer  THANKS :)

**Comment by mfidemraizer** [comment]
@HamedFathi Thanks to you and the other guy from #28, because I wanted to do the effort to port the library to .NET Standard, but you both have been an incentive to move forward!

For now, I'm going to close this issue :)
