### ISSUE TITLE
Incorporate existing interfaces in System.ComponentModel

### ISSUE THREAD

**Issue by weitzhandler** [mfidemraizer/trackerdog#31]
Hi and thanks for this wonderful lib and for sharing your effort!

It would be nice to have some of the interfaces in the [`System.ComponentModel`](https://msdn.microsoft.com/en-us/library/system.componentmodel) namespace such as `IRevertibleChangeTracking` (that implements `IChangeTracking`) and some others.

**Comment by mfidemraizer** [comment]
Thank you for your good comments about the lib! 

I'll take a look at this in the next days

**Comment by mfidemraizer** [comment]
Some question: *which are those other interfaces*?

**Comment by mfidemraizer** [comment]
@weitzhandler I've already implemented `IRevertibleChangeTracking`. If you check the code on the commit you'll see how easy was the task ;D 

In the other hand, I've created a temp branch to advance on implement the other (yet unknown by me) interfaces you mention in your first comment.

**Comment by weitzhandler** [comment]
Thank you!

**Comment by mfidemraizer** [comment]
@weitzhandler BTW, which are those other interfaces you pointed in your first comment?

**Comment by weitzhandler** [comment]
You mean [this](https://msdn.microsoft.com/en-us/library/system.componentmodel.irevertiblechangetracking)?

**Comment by weitzhandler** [comment]
I'm just shooting out, you pick what you see fit:
- [`ICancelAddNew`](https://msdn.microsoft.com/en-us/library/system.componentmodel.icanceladdnew)
- [`IEditableObject`](https://msdn.microsoft.com/en-us/library/system.componentmodel.ieditableobject)
- [`INotifyPropertyChanging`](https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifypropertychanging)[<sup>*</sup>](https://github.com/dotnet/corefx/issues/19627)

Thanks for your dedication, I'm sure one day I'll use your project, unfortunately in the project I'm currently working on, I'm using the [Prism](/PrismLibrary/Prism), which currently doesn't support .NET Standard 😢
