### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by weitzhandler** [mfidemraizer/trackerdog#32]
Unable to install into my Xamarin PCL (profile 44) project.

**Comment by mfidemraizer** [comment]
This is because TrackerDog isn't a PCL: it's a .NET Standard library, which is in turn the replacement to PCL. Probably, not just because you want to use TrackerDog, it should be time to migrate your PCLs to the new .NET Standard library paradigm.

**Comment by weitzhandler** [comment]
Until Xamarin adopts .NET standard is gonna take a year...
I thought it's been targeted for Xamarin too, seeing the nice Xamarin icon in the README haha. Do you plan anything on the subject soon?

**Comment by mfidemraizer** [comment]
Check this chart: https://docs.microsoft.com/en-us/dotnet/articles/standard/library

Maybe I'm mistaken, but .NET Standard-compliant libs should work on Xamarin.

**Comment by weitzhandler** [comment]
The newest Xamarin is targeting Profile44, which is [netstandard 1.2](pcl-compatibility).

**Comment by weitzhandler** [comment]
The newest (it will never remain newest...) Xamarin is targeting [Profile44](https://docs.microsoft.com/en-us/dotnet/articles/standard/library#pcl-compatibility), which is [netstandard 1.2](http://danrigby.com/2014/05/14/supported-pcl-profiles-xamarin-for-visual-studio-2), as well as the wider but older Profile121. Profile44 only targets UWP, Droid and iOS, neglecting Silverlight and some other dying technologies, whilst 121 includes WP8.1 too.
Is it possible to downgrade TrackerDog to 1.2 to open it for Xamarin?

**Comment by mfidemraizer** [comment]
Hey, it's impossible to downgrade TrackerDog to .NET Standard 1.2 because Castle Core requires at least .NET Standard 1.3.

About Silverlight, I wouldn't put effort on this... You know, it's a completely dead technology. Would you drop .NET Core support to support Silverlight?

**Comment by mfidemraizer** [comment]
BTW, can you elaborate on why [this compatibility table](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) says the opposite? It seems like you should be able to switch your PCL to .NET Standard libs.

**Comment by weitzhandler** [comment]
You're right. I am currently using [Prism](/PrismLibrary/Prism), and that doesn't have .NET standard support. [What a shame](/PrismLibrary/Prism/issues/683)!
