### ISSUE TITLE
DTO of graph change data

### ISSUE THREAD

**Issue by weitzhandler** [mfidemraizer/trackerdog#33]
Please create a contract that will enable transmitting object-change data of a graph in a hierarchical, yet enumerable manner.

Any DTO would be sufficient, but to take it a step further it can be made complex. Here are some examples:

- Create 2 contract types
  - Contract of change data from client to server
  - Contract of changes that were applied (such as IDs etc.) or ignored (invalid or orphaned entities etc.)
- Minify DTO size
  - Omit unchanged fields
  - Do include ID fields and some others by naming convention / config, omit them when 0/null/new
  - Each row should have a unique ID to be recognize back in the client when there are issues
- A means of swallowing returned data from server, and undo/throw/update according to what's received from server

Supplied to server (json?):

Each row should contain object, desired action, and new values if any.

* Person [unchanged]
  * Id 1
  * FirstName [changed] (newvalue)
  * Phones
    * Phone [new]
    *  Id 0
    * Phone
      * Id 1
      * Number [changed] new value
   * Phone [deleted]
     * Id 2
* Person with phones [deleted]
  * Id 2

Server will perform
Returned from server [desired action]{result}(values?)

* Person [unchanged][none]
  * Id 1
  * Phone [new]
    * Id {changed} (3)
  * Phone
    * Id 4
    * Number [changed]{rejected}
* Person [deleted]{rejected}

**Comment by mfidemraizer** [comment]
Lets deeply discuss about this topic.

First of all, would you agree that we should implement [Set-Unset](http://designpattern.ninja/catalog/design-patterns/setunset) and [Create-Update-Delete collection pattern](http://designpattern.ninja/catalog/design-patterns/create-update-delete-collection) patterns to taylor the whole DTO?

The other problem is that the whole DTO should be provided by the developer, or TrackerDog should provide a T4 code generation feature to generate these DTOs from change-tracked types...

**Comment by weitzhandler** [comment]
I believe at least at first, the dev should provide the full Entities and their DTOs and mapping, and the client should provide the server only with what's needed to be saved/changed/added and omit the rest of the properties of the JSON. JSON library will know how to deal with the non-existent fields and construct them to their defaults.
What TrackerDog should provide IMHO is an external wrapper contract that contains a tree/graph, and for each container (class, or non-primitive-type propretry in root) in the tree, info about it's state (new, updated, deleted), and the name of the relevant fields, if selective (so to ignore the default values e.g. 0 for int). DTO generation could be nice, but I don't think you'd have to start from there, it might expand TrackerDog to where you don't want it to.

**Comment by mfidemraizer** [comment]
@weitzhandler Hey, in fact, [ObjectPropertyChangeTracking](https://github.com/mfidemraizer/trackerdog/blob/v2/TrackerDog/ObjectPropertyChangeTracking.cs) is the starting point to build that tree.

Probably that tree could be expressed as a `IDictionary<TKey, TValue>` where *values* would be instances of a new DTO called like `ChangeTrackedObjectInfo` or something like that which would provide the whole info.

Most of the required info is already in  [ObjectPropertyChangeTracking](https://github.com/mfidemraizer/trackerdog/blob/v2/TrackerDog/ObjectPropertyChangeTracking.cs) and  [DeclaredObjectPropertyChangeTracking](https://github.com/mfidemraizer/trackerdog/blob/v2/TrackerDog/DeclaredObjectPropertyChangeTracking.cs)

**Comment by weitzhandler** [comment]
Right. The key has to be more complex tho, and then there is the result DTO, i.e. what was updated/rejected by server.
Each entity in graph needs to get a unique ID besides its usual one, since it can be a new entity, and we need to identify on server result.

**Comment by mfidemraizer** [comment]
One question, do you need this right now? ;D I ask you this to prioritize this feature or not.

**Comment by weitzhandler** [comment]
Not really. In fact I can't use TrackerDog at all in the project we're currently working on, because It's tied down to be PCL. But in a previous issue you told me to open a new one so I did just for the discussion and the reference for the future.

**Comment by mfidemraizer** [comment]
I see. Well, let's stay this issue as *open* and if someone requires this, I'll put the effort to implement the whole requirement!

**Comment by weitzhandler** [comment]
Actually, I think, a simple interface exposing elementary data about all changes would be sufficient, here's a rough prototyping shot, I believe that most of the features are already there, it's just needs a bit of reorganization and exposing in the right way. It can be way cleaner and less features or in a nicer way. I'm sure you get the general idea.

It's important to have the proxy class implementing a public interface that inherits all the actual implementations, and some sort of fake DTO to pass it (only including changed/added/deleted properties and collection-properties as JSON) and read it to and by the server, the in the server we can walk the graph and attach only what's needed. So instead of the config.TrackThisType etc. returns an unknown proxy type, the proxy returns a centeralized interface that can be the wrapped in as a class.

Again, I'm just shooting off an idea, I'm sure you'll find the better way how to implement this.

```
interface ITrackedObject : INotifyPropertyChanging, INotifyPropertyChanged,
  IRevertibleChangeTracking, IEditableObject
{
    //primitive values property/value
    Dictionary<string, object> ChangedPropertyValues { get; }
    //navigation properties - complext types
    IReadOnlyCollection<ITrackedObject> TrackedChildren { get; }
    IReadOnlyCollection<ITrackedObject> ChangedChildren ( => 
      TrackedChildren.Where(to=> to.ObjectState == ObjectState.Changed) etc.
    IReadOnlyCollection<ITrackedObject> AddedChildren { get; }
    IReadOnlyCollection<ITrackedObject> RemovedChildren { get; }    
    object GetPropertyValue(string propertyValue);

    IReadOnlyCollection<ITrackedObject> RecursiveAllChildren { get; }

    //collection properties
    IReadOnlyCollection<ITrackedObjectCollection> TrackedCollections { get; }
    //changed ones, added ones.
    ObjectState State { get; (set;) }

    void BeginTracking();
    void EndTracking();
}

interface ITrackedObjectCollection : INotifyCollectionChanged, INotifyPropertyChanged, 
INotifyPropertyChanging, IEditableCollection, IEditableCollectionViewAddNewItem, 
IList<ITrackedObject>
{
    void BeginTracking();
    void EndTracking();
    //....
}

enum ObjectState { Unchanged, Added, Changed, Deleted }

//this should be a DTO of the tracked object to be constructed on server from the json received
public class ChangeDataDto(<TObject>?) : ITrackedObject
{
    //not sure how here
    ctor(ITrackedObject object, bool ignoreUnchangedData);
    public TObject TrackedObject { get; set; }
    //all properties and collection properties in the tree
}
```

Usage in client, before sending to server

    var trackedUser = config.TrackThisType(....user);
    trackedUser.UserName = "new user name";
    var trackData = (ITrackedObject)trackedUser;

   //now we can recurse thru all the changed properties and children,
   // and send to the server only the relevant data
    var json = ExtractChangeData(trackData);
    var result _Client.Save(json)

Then in server:

    public Task<IActionResult> Put(TrackedObject<User> user)
    {
        //walk thru all changed/added/removed children/collections
        // and attach them to the context appropriately then save
    }

**Comment by mfidemraizer** [comment]
Thank you for giving ideas. I'll pay attention to your proposal! 👍
