### ISSUE TITLE
Same value, object should be in unchanged state!!

### ISSUE THREAD

**Issue by toumir** [mfidemraizer/trackerdog#38]
Hi,
...
`IObjectChangeTracker changeTracker = user.GetChangeTracker();`
...
initially user age is 0 // default value
//change it here 
`user.Age = 41;`
//change it again back to the old value 0
`user.Age = 0;`
When I check for property changes:
`changeTracker.ChangedProperties.Any() //<=should return false since it equals to the old value! `

idem form the complex and collections properties!
can guide me ?

**Comment by mfidemraizer** [comment]
Oops! This is unexpected. I'll try to reproduce the issue and I'll be back to you.

**Comment by toumir** [comment]
I think I'm a wrong the test pass 
`[TestMethod]
        public void SameValueObjectStayInUnchangedState()
        {
            const string initialValue = "hello world";
            A a = TrackableObjectFactory.CreateFrom(new A { Text = initialValue });
            IObjectChangeTracker changeTracker = a.GetChangeTracker();

            Assert.AreEqual(0, changeTracker.ChangedProperties.Count);
            Assert.AreEqual(2, changeTracker.UnchangedProperties.Count);
            a.Text = initialValue;

            Assert.AreEqual(0, changeTracker.ChangedProperties.Count);
            Assert.AreEqual(2, changeTracker.UnchangedProperties.Count);
        }`

**Comment by toumir** [comment]
Hi,
When testing the behavior, the test pass (I added a test method to your tests project)


```[TestMethod]
public void AffecttheSameValueObjectStayInUnchangedState()`
{ 
	const string initialValue = "hello world";
	A a = TrackableObjectFactory.CreateFrom(new A { Text = initialValue }); 
	IObjectChangeTracker changeTracker = a.GetChangeTracker();
	Assert.AreEqual(0, changeTracker.ChangedProperties.Count);
	Assert.AreEqual(2, changeTracker.UnchangedProperties.Count);

	a.Text = "another value"; 
	a.Text = initialValue; 

	Assert.AreEqual(0, changeTracker.ChangedProperties.Count); 
	Assert.AreEqual(2, changeTracker.UnchangedProperties.Count);
}
```
**but in production we get different result**
I'm using Linqpad for simplicity:

```
public class User
{ 
	public virtual string Name { get; set; } 
	public virtual byte Age { get; set; } 
	public virtual Adresse Adresse{ get; set; } 
}

public class Adresse
{
	public virtual string Region{get;set;} 
}

IObjectChangeTrackingConfiguration config = ObjectChangeTracking.CreateConfiguration();
config.TrackThisType(t=> t.IncludeProperties(u=>u.Name, u=>u.Age, u=>u.Adresse));
config.TrackThisType(t=> t.IncludeProperties(r=>r.Region));

ITrackableObjectFactory trackableObjectFactory = config.CreateTrackableObjectFactory();
User user = trackableObjectFactory.CreateOf<User>();

IObjectChangeTracker changeTracker = user.GetChangeTracker();
changeTracker.ChangedProperties.Any()//<= return false
user.Age = 41;
user.Age = 0;
changeTracker.ChangedProperties.Any()//<= return true
```
**correct me if I'm wrong**
thanks for your time

**Comment by toumir** [comment]
FYI: it seems its works with string values but not for int values, very strange!!!
changing The test above :
with string properties =>test passes, 
with int properties=> test fails
thanks for your time

**Comment by toumir** [comment]
tested for complex properties, test fails : here is the full example
```
void Main()
{
	IObjectChangeTrackingConfiguration config = ObjectChangeTracking.CreateConfiguration();
	config.TrackThisType<User>(t=> t.IncludeProperties(u=>u.Name, u=>u.Age, u=>u.Adresse));
	config.TrackThisType<Adresse>(t=> t.IncludeProperties(r=>r.Region));
	ITrackableObjectFactory trackableObjectFactory = config.CreateTrackableObjectFactory();
	
	int initVal 	= 10;
	string initName	="red";
	var initAdresse = new Adresse{Region="MEDEA"};
	var adresse2 	= new Adresse{Region="MEDEA"};

	User user = trackableObjectFactory.CreateFrom(new User{Name=initName, Age=initVal,Adresse = initAdresse});
	IObjectChangeTracker changeTracker = user.GetChangeTracker();
	
	changeTracker.ChangedProperties.Count.Dump("# of properties changed"); 
	changeTracker.UnchangedProperties.Count.Dump("# of properties unchanged"); 
	
	user.Adresse = adresse2;
	user.Adresse = initAdresse;//back init value
	
	user.Name="test";
	user.Name=initName;//back init value
	
	user.Age =100;
	user.Age=initVal; //back init value
	
	changeTracker.ChangedProperties.Count.Dump("#changed");
	changeTracker.UnchangedProperties.Count.Dump("#unchanged");
	
	//list properties changed 
	Debug.WriteLine("changed properties");
	var pptz  = changeTracker.ChangedProperties;
	foreach (var ppt in pptz)
	{
		ppt.PropertyName.Dump();
	}


	//output
	/*
		#changed
		0 
	
		#unchanged
		4 
	
		#changed
		2 
	
		#unchanged
		2 
		changed properties
		Age
		Adresse
	*/
}

public class User
{
	public virtual string Name { get; set; }
	public virtual int Age { get; set; }
	public virtual Adresse Adresse{ get; set; }
}
public class Adresse
{
	public virtual string Region{get;set;}
}

```

**Comment by mfidemraizer** [comment]
Thank you for the details

I'll take a look tomorrow :+1:

**Comment by toumir** [comment]
still waiting a response
Is there anyone to answer my question?!

**Comment by mfidemraizer** [comment]
@toumir Sorry, I've a hard work these days to have room to be at my PC. 

BTW, now I'm going to spend some time to check your issue. I hope it'll be easy to fix!

**Comment by mfidemraizer** [comment]
@toumir I hope I'll be able to run the code today. It has been some months since I opened the virtual machine on which I can run a full framework and dotnet core side by side project (which is the case of TrackerDog).

Now that I've been able to run the whole VM, Windows 10 is updating, argh! :-1:

**Comment by toumir** [comment]
Thanks for your time 👍

**Comment by mfidemraizer** [comment]
@toumir No problem ;)

I could reproduce the issue with your code in my dev machine.

My first impression is that it should be a bug, because when I get the property tracking, its old value is valid and both old and new values equal (i.e. `o.GetPropertyTracking(x => x.Age)`). 

So I'm going to check what's wrong with `ChangedProperties` calculated property.

**Comment by mfidemraizer** [comment]
@toumir Solved! At least, the thing with integers.

The problem was [here](https://github.com/mfidemraizer/trackerdog/blob/dc3c6f34f2b32359b44b334a5510a4f97e679dc7/TrackerDog/DeclaredObjectPropertyChangeTracking.cs#L94)

Changing that line to `return (bool)!CurrentValue?.Equals(OldValue);` has solved the issue.

This code was using `==`. Operator overloading isn't inherited. That is, a boxed integer as `object` wasn't using its equality implementation. That resulted on `0 == 0` being `false`, thus, TrackerDog thought that integer properties were changed.

Let me know if you're on full framework or .NET Core. I'll give you an assembly so you may try the fix prior to publish it to NuGet.

**Comment by mfidemraizer** [comment]
@toumir About complex types, you'll need to implement `IEquatable<T>` on that types. Otherwise, the equality will be based on references instead of property values.

**Comment by mfidemraizer** [comment]
Anyway, here you can download both NetStandard and FullFramework's assemblies:

[TrackerDog.NetStandard.zip](https://github.com/mfidemraizer/trackerdog/files/1595171/TrackerDog.NetStandard.zip)

[TrackerDog.FullFramework.zip](https://github.com/mfidemraizer/trackerdog/files/1595172/TrackerDog.FullFramework.zip)

Let me know if this solved your issue!

**Comment by toumir** [comment]
Hi @mfidemraizer, 
I made the change you proposed but, when run the tests(yours), get 13 tests fails, what do you think
Thanks in advance

**Comment by toumir** [comment]
can you provide me more information where to put the changes, may be I put it in the wrong place file

**Comment by mfidemraizer** [comment]
@toumir hey

Sorry, I should've edit that previous comment. I also ran the tests and finally the whole issue gets fixed as follows:

```c#
if (CurrentValue == null && OldValue == null)
   return false;
else
   return !(bool)CurrentValue?.Equals(OldValue);
```

Please try it again and let me know if you solved the issue 🗡 

And, what about `IEquatable<T>`? Have you already implemented it in your classes?

**Comment by toumir** [comment]
My test method, :( still not working!
```
[TestMethod]
        public void SameValueObjectStayInUnchangedState2()
        {
            const int initialValue = 10;

            User user = TrackableObjectFactory.CreateFrom(new User { Age = initialValue });

            IObjectChangeTracker changeTracker = user.GetChangeTracker();

            Assert.AreEqual(0, changeTracker.ChangedProperties.Count);
            Assert.AreEqual(1, changeTracker.UnchangedProperties.Count);

            user.Age = 41;
            user.Age = initialValue;

            Assert.AreEqual(0, changeTracker.ChangedProperties.Count);
            Assert.AreEqual(1, changeTracker.UnchangedProperties.Count);
        }
```

**Comment by mfidemraizer** [comment]
@toumir Where have you placed the new assembly (i.e. `trackerdog.dll`)? You should overwrite the one found in `/packages` and rebuild your solution/project.

**Comment by toumir** [comment]
apropos  IEquatable<T>, I did this on another project, try todo it here

**Comment by mfidemraizer** [comment]
@toumir Are you in Gitter?

**Comment by toumir** [comment]
sorry I'm not an English man, I take time to understand you :) what do you mean by Gitter

**Comment by mfidemraizer** [comment]
@toumir I'm not native English speaker too, I'm Spanish!

Uhm, it's an app/webapp on which many developers talks, usually from GitHub: https://gitter.im

You can sign up there using your GitHub account. Why don't we continue the chat there? Once we solve the issue, we put here our conclusions. Search me in Gitter by my GitHub user: **mfidemraizer**

**Comment by toumir** [comment]
got it i'm in gitter
