### ISSUE TITLE
Fire Changed event if the object changes back to unchanged

### ISSUE THREAD

**Issue by markgould** [mfidemraizer/trackerdog#40]
Is there a reason the Changed event doesn't fire if an object was changed (it fires) and is then changed back?

We have a visual indicator on the screen that shows the user if there are changes, so on the Changed event I have some code that looks like "HasChanges = Tracker.ChangedProperties.Any();" which works when a property changes, but when it changes back (testing with a simple checkbox) it doesn't fire.

In ObjectChangeTracker i see that Changed is only invoked if HasChanged is true. Is there any harm in firing this regardless? Or is there a better way to achieve what I want?

**Comment by markgould** [comment]
I may have posted this too soon - I guess simply using the PropertyChanged event will suffice. I did not realize it would fire on a parent object for even nested collection items. Awesome!

**Comment by mfidemraizer** [comment]
@markgould Nice to know you solved the doubt yourself! ;-)
