### ISSUE TITLE
Is it possible to track existing objects?

### ISSUE THREAD

**Issue by krispharper** [mfidemraizer/trackerdog#47]
I might have a misunderstanding of how to use TrackerDog. If I have an existing object, say

```
User user = new User();
user.Name = "John";
user.Age = 32;
```

and then I try to add it to be tracked

```
trackedUser = trackableObjectFactory.CreateFrom(user);
```

then the resulting `trackedUser` object I get is missing the values that were previously set on it. I.e., `Name` will be `""` and `Age` will be `0`.

Is this the intended behavior? Is there any way to start tracking an existing object without resetting it? It's a little confusing because it seems like even though I pass in the `user` object to `CreateFrom`, the `User` parameterless constructor is still called. So I'm not sure what the point of that method is if that's the case. It seems like it could just be replaced by `CreateOf<T>`.

**Comment by toumir** [comment]
Hi @krispharper 
I confirm that there is no problem and the [documentation](http://matiasfidemraizer.com/trackerdog/html/52e40f26-3dfe-47e0-adf1-09233e98f42e.htm#objects2trackable) explains things very well : take a look at the following LinqPad script : 

```
void Main()
{
	IObjectChangeTrackingConfiguration config = ObjectChangeTracking.CreateConfiguration();
	config.TrackThisType<User>();
	
	ITrackableObjectFactory trackableObjectFactory = config.CreateTrackableObjectFactory();

	User user = new User();
	user.Name = "John";
	user.Age = 32;
	
	User trackableUser = trackableObjectFactory.CreateFrom(user);
	
	trackableUser.Name.Dump(); //John
	trackableUser.Age.Dump();  //32
}

public class User
{
	public virtual string Name { get; set; }
	public virtual byte Age { get; set; }
}
```

**Comment by mfidemraizer** [comment]
@krispharper Hi! And thank you for using TrackerDog!

I suspect that your properties aren't `virtual`. Am I mistaken?

**Comment by mfidemraizer** [comment]
@krispharper Hi! Thank you for using TrackerDog!

May you confirm that you forgot to configure the whole type as a *trackable type* as @toumir has already pointed out?

**Comment by krispharper** [comment]
Ah, it was indeed that my properties weren't `virtual`. I had forgotten that requirement. It looks like it's working with that in place.

Thanks for the help.
