### ISSUE TITLE
Get Root Object of Tracker Graph

### ISSUE THREAD

**Issue by ordinaryorange** [mfidemraizer/trackerdog#8]
I'm implementing the new `Changed` event in my application.

Using the example in our other discussions, if I do `a.B.C.Text = "new text"` the event fires.
And the event args `TargetObject` is C as expected.
What I need to do now is find C's root object i.e. `a`

I see there is `Target` property on the `DeclaredObjectPropertyChangeTracking` class but it is internal, so for now I've added an ugly hack to access this property via reflection so I can determine the root element. i.e.
```
var trackedGraphInstances = e.PropertyChangeTracking.Tracker.Select(t => t.GetType().GetProperty("TargetObject").GetValue(t));
var root = GetRoot(trackedGrahpInstances); //custom method to find root.
```
Can I request another mod ?
Options could be
Add a `Parent` property to the proxy (not sure I like this)
Add a `GetRoot()` to the tracker (bit limited in functionality)
Add a `FindAncestor()` to the proxy with various overloads for specifying a type, instance, and getting of the root ?

Let me know if you think this should be included in TrackerDog or if there is an alternative way that I'm overlooking.
Thanks

**Comment by mfidemraizer** [comment]
I'll take a look at this. Probably it should be a public `ParentProperty` property on `IDeclaredPropertyChangeTracking` interface. 

I don't know if I'll manage to give you a solution today but I'll try to give it as soon as possible (1-2 days!).

**Comment by mfidemraizer** [comment]
I forgot to said that I'm glad you're providing a lot of feedback! This is very nice, you're demonstrating why open-sourcing projects is a great way of not only enhancing them but also to improve my and everyone's skills!

**Comment by ordinaryorange** [comment]
Yeah same here, one learns lots by reading other peoples code.
No rush on the mods, I've got temporary workaround code for the interim so I can keep moving forward on my app. Once the the latest and greatest TrackerDog is on nuget, I'll delete the workarounds and implement the shiny features.
Thanks for you interest in adding in the features.

**Comment by mfidemraizer** [comment]
I've pushed a new NuGet package as version 1.2.3.

Now `IObjectChangeTracking` publishes `TargetObject`. 

BTW, I'm not sure if it may or may not be useful in your case, but you should explore what `TrackableType.ObjectPaths` can give you. It's a still undocumented feature I required internally but that you can take advantage of it in your own developments.

It gives you a list of `IObjectPropertyInfo` where you gain access to all tracked type property paths. For example "A.B.C", "A.B". And it also gives you them as instances of `PropertyInfo`.

You can explore what you can get of `TrackableType.ObjectPaths` property this way:

```
ITrackableType a = typeof(A).GetTrackableType();
IImmutableList<IObjectPropertyInfo> paths = a.ObjectPaths;
```

I'm not absolutely sure about that, but what I give you with publishing `TargetObject`  and what `ITrackableType` interface gives you, it should solve your scenario very well!

**Comment by mfidemraizer** [comment]
@ordinaryorange  Please tell me if I can close this issue too. Does my solution *solves* your concrete scenario?

**Comment by ordinaryorange** [comment]
Not quite getting what I'm after with this mod.
Here a specific example of the implemented mod to try to better explain the requirement.
When `Changed` event fires in the below, the `TargetObject` object is typeof `C`. If I call the object paths from here I only get descendant paths. I need ancestor paths so I can find root object of type `A`

```
void Main()
{
	TrackerDog.Configuration.TrackerDogConfiguration.TrackTheseTypes(Track.ThisType<A>(), Track.ThisType<B>(), Track.ThisType<C>());  
	var a = new A();
	var b = new B();
	var c = new C();
	a.B = b;
	b.C = c;
    var aa = a.AsTrackable();
	aa.GetChangeTracker().Changed += (sender, args) => args.PropertyChangeTracking.TargetObject.GetActualTypeIfTrackable().GetTrackableType().ObjectPaths.Dump();
	aa.B.C.MyProperty = 10;
}

public class A 
{
	public virtual B B { get; set; }
}

public class B
{
	public virtual C C { get; set; }
}

public class C
{
	public virtual int MyProperty { get; set; }
}
```

**Comment by mfidemraizer** [comment]
Uhm, I'll take a further look at this. I'm sure we'll find the best solution!

**Comment by mfidemraizer** [comment]
I'm still working on this. The final solution will be getting a dictionary of properties to property trackings in order. The order is *the hierarchy*.

For example, Let's say `A` has an association with `B`, and `B` has an association with `C`. You'll get a list of property trackings where the first item will the tracking for `A`, `B` and `C`.

I believe that this should satisfy your requirement!

**Comment by mfidemraizer** [comment]
Here's a working sample, let me know if I'm in the right track:

![graph](https://cloud.githubusercontent.com/assets/820748/17181394/491b1c78-5420-11e6-8b85-85972689d055.png)

And it's got using the following method of `IObjectChangeTracker`:

`var x =  changeTracker.GetTrackingHierarchyForProperty(typeof(B).GetProperty("C"));
`

**Comment by ordinaryorange** [comment]
Well if the dictionary is ordered, then index 0 would be root, am i right ?
Whilst that would work and do for now, a future more intuitive approach might be to create a type of class like the VisualTreeHelper for WPF/Silverlight. This static class has a GetParent() and the silverlight version has a GetRoot(). just ideas.

**Comment by mfidemraizer** [comment]
@ordinaryorange  Yesterday I could advance this feature even more and `Associations` will be called `AggregateHierarchy` and it's an `IImmutableList<T>`. And yes, **items in that list are ordered by how deep is a given property tracking within the object graph**.

BTW, the root is impossible to include inside the whole list, because it's not a property, but the object itself, so you'll find it in `Parent` property.

For example, let's say you've the following hierarchy:

A a = new A();
C c = a.B.C;

Once you got the object graph info with our new shiny method, you'll get `C` and `B` as property trackings and `A` will be the `Parent` property.

Is it fine, isn't it?

**Comment by mfidemraizer** [comment]
@ordinaryorange  I forgot to mention that `ObjectChangeEventArgs` will give you the whole hierarchy info directly, because if I didn't understand you wrongly, you need this info there and  I want to save you from calling the whole method manually and you'll avoid using *reflection* in your project code for this!

**Comment by ordinaryorange** [comment]
The parent property will be perfect for my needs.  
I did already extensively inspect the `ObjectChangeEventArgs` before posting this issue. The only place I could locate the object hierachy was in my hack code as in my opening post.
Either way, the shiny new method will be much nicer, I look forward to testing it.

**Comment by mfidemraizer** [comment]
@ordinaryorange Ok, let's see if I can have some spare time today because it seems like it works but 2 unrelated tests are failing. Once I got everything working, I'll be back here again!

**Comment by mfidemraizer** [comment]
Done! Try it on NuGet package version 2.0.0!
